// 배포 후 OWNER/REPOSITORY를 실제 GitHub 저장소 경로로 바꾸세요.
const ISSUE_URL = 'https://github.com/presentjinho/newsletter-hub/issues/new/choose';

const newsletters = [
  { id:'newneek', name:'뉴닉', category:'시사', frequency:'매일', frequencyGroup:'daily', description:'세상이 궁금한 사람들을 위한 쉽고 친절한 뉴스.', url:'https://newneek.co/', daysSince:0, typical:'평일 아침', status:'alive', interests:['시사','재테크'], trust:['최근 30일 발행','공식 구독 링크 확인'] },
  { id:'outstand', name:'아웃스탠딩', category:'비즈니스', frequency:'평일', frequencyGroup:'daily', description:'스타트업과 IT 비즈니스의 맥락을 깊게 읽습니다.', url:'https://outstand.co.kr/', daysSince:0, typical:'평일', status:'alive', interests:['AI','커리어','재테크'], trust:['최근 30일 발행','공식 구독 링크 확인','유료 포함'] },
  { id:'stibee', name:'스티비', category:'마케팅', frequency:'주 1회', frequencyGroup:'weekly', description:'이메일 마케팅과 뉴스레터를 잘 만드는 법.', url:'https://stibee.com/', daysSince:1, typical:'보통 화요일', status:'alive', interests:['디자인','커리어'], trust:['최근 30일 발행','공식 구독 링크 확인'] },
  { id:'geeknews', name:'긱뉴스', category:'테크', frequency:'매일', frequencyGroup:'daily', description:'개발자와 기술 애호가가 함께 고르는 오늘의 링크.', url:'https://news.hada.io/', daysSince:0, typical:'매일 오전', status:'alive', interests:['AI','커리어'], trust:['최근 30일 발행','공식 구독 링크 확인'] },
  { id:'longblack', name:'롱블랙', category:'라이프', frequency:'매일', frequencyGroup:'daily', description:'하루 한 편, 오래 남는 브랜드와 사람의 이야기.', url:'https://www.longblack.co/', daysSince:0, typical:'매일 오전 7시', status:'alive', interests:['디자인','커리어'], trust:['최근 30일 발행','공식 구독 링크 확인','유료 포함'] },
  { id:'beletter', name:'비레터', category:'마케팅', frequency:'주 2회', frequencyGroup:'weekly', description:'광고와 브랜드 업계의 흐름을 재치 있게 정리합니다.', url:'https://www.beletter.co.kr/', daysSince:2, typical:'화·목요일', status:'alive', interests:['디자인','커리어'], trust:['최근 30일 발행','공식 구독 링크 확인','광고성 높음'] },
  { id:'maily', name:'메일리', category:'라이프', frequency:'가끔', frequencyGroup:'occasional', description:'좋아하는 작가의 글을 메일함으로 받는 구독 플랫폼.', url:'https://maily.so/', daysSince:1, typical:'작가별 상이', status:'alive', interests:['디자인','커리어'], trust:['공식 구독 링크 확인'] },
  { id:'weekly', name:'위클리비즈', category:'비즈니스', frequency:'주 1회', frequencyGroup:'weekly', description:'일하는 방식과 비즈니스 인사이트를 전합니다.', url:'https://www.chosun.com/economy/', daysSince:6, typical:'보통 월요일', status:'paused', interests:['재테크','커리어'], trust:['공식 구독 링크 확인'] },
  { id:'publy', name:'퍼블리', category:'커리어', frequency:'주 1회', frequencyGroup:'weekly', description:'일과 성장에 필요한 지식을 차분히 전합니다.', url:'https://publy.co/', daysSince:1, typical:'보통 수요일', status:'alive', interests:['커리어','디자인'], trust:['최근 30일 발행','공식 구독 링크 확인','유료 포함'] }
];

newsletters.forEach(item => Object.assign(item, { origin:'한국', language:'한국어', country:'대한민국' }));
newsletters.push(
  { id:'morning-brew', name:'Morning Brew', category:'비즈니스', frequency:'평일', frequencyGroup:'daily', description:'비즈니스·경제의 큰 흐름을 약 5분 안에 유쾌하게 훑는 글로벌 데일리.', url:'https://www.morningbrew.com/', daysSince:0, typical:'평일 아침', status:'alive', interests:['재테크','커리어'], trust:['공식 구독 링크 확인','무료','글로벌 인기'], origin:'글로벌', language:'영어 · 소개 한국어' },
  { id:'tldr', name:'TLDR', category:'테크', frequency:'매일', frequencyGroup:'daily', description:'기술·스타트업·개발 소식을 짧은 요약과 링크로 정리하는 데일리.', url:'https://tldr.tech/signup', daysSince:0, typical:'매일', status:'alive', interests:['AI','개발','커리어'], trust:['공식 구독 링크 확인','무료','글로벌 인기'], origin:'글로벌', language:'영어 · 소개 한국어' },
  { id:'rundown-ai', name:'The Rundown AI', category:'테크', frequency:'매일', frequencyGroup:'daily', description:'AI 뉴스와 실제 업무 활용법을 빠르게 확인하고 싶은 사람을 위한 브리핑.', url:'https://www.therundown.ai/', daysSince:0, typical:'평일', status:'alive', interests:['AI','개발','커리어'], trust:['공식 구독 링크 확인','무료','글로벌 인기'], origin:'글로벌', language:'영어 · 소개 한국어' },
  { id:'the-hustle', name:'The Hustle', category:'비즈니스', frequency:'평일', frequencyGroup:'daily', description:'스타트업과 비즈니스 뉴스를 직설적이고 가볍게 풀어 주는 데일리.', url:'https://thehustle.co/join', daysSince:0, typical:'평일 오전', status:'alive', interests:['재테크','커리어'], trust:['공식 구독 링크 확인','무료','글로벌 인기'], origin:'글로벌', language:'영어 · 소개 한국어' },
  { id:'stratechery', name:'Stratechery', category:'테크', frequency:'주 1회', frequencyGroup:'weekly', description:'기술 기업과 플랫폼 전략을 깊이 있는 해설로 읽는 분석형 뉴스레터.', url:'https://stratechery.com/', daysSince:1, typical:'주간 글 · 데일리 업데이트 선택', status:'alive', interests:['AI','재테크','커리어'], trust:['공식 구독 링크 확인','유료 포함','글로벌 인기'], origin:'글로벌', language:'영어 · 소개 한국어' },
  { id:'the-browser', name:'The Browser', category:'문화', frequency:'평일', frequencyGroup:'daily', description:'기사·팟캐스트·영상에서 좋은 것만 고르고 한 단락으로 맥락을 전하는 큐레이션.', url:'https://thebrowser.com/', daysSince:0, typical:'평일 · 주말 특집', status:'alive', interests:['문화','시사','디자인'], trust:['공식 구독 링크 확인','유료 포함','글로벌 인기'], origin:'글로벌', language:'영어 · 소개 한국어' },
  { id:'dense-discovery', name:'Dense Discovery', category:'디자인', frequency:'주 1회', frequencyGroup:'weekly', description:'디자인·기술·예술을 천천히 생각하게 만드는 엄선된 주간 링크 모음.', url:'https://www.densediscovery.com/', daysSince:1, typical:'주 1회', status:'alive', interests:['디자인','문화','커리어'], trust:['공식 구독 링크 확인','무료','글로벌 인기'], origin:'글로벌', language:'영어 · 소개 한국어' }
);

newsletters.push(
  { id:'three-two-one', name:'3-2-1 Thursday', category:'자기계발', frequency:'주 1회', frequencyGroup:'weekly', description:'3가지 아이디어, 2가지 인용, 1가지 질문으로 습관과 삶을 돌아보게 하는 짧은 주간 편지.', url:'https://jamesclear.com/3-2-1', daysSince:1, typical:'매주 목요일', status:'alive', interests:['커리어','건강','문화'], trust:['공식 구독 링크 확인','무료','글로벌 인기'], origin:'글로벌', language:'영어 · 소개 한국어' },
  { id:'hbr-tip', name:'HBR Management Tip', category:'리더십', frequency:'평일', frequencyGroup:'daily', description:'일을 더 잘하기 위한 짧고 실용적인 관리·리더십 팁을 전하는 데일리.', url:'https://hbr.org/email-newsletters', daysSince:0, typical:'평일', status:'alive', interests:['커리어','리더십','자기계발'], trust:['공식 구독 링크 확인','글로벌 인기'], origin:'글로벌', language:'영어 · 소개 한국어' }
);

newsletters.push(
  { id:'folin', name:'폴인', category:'스타트업', frequency:'주 2회', frequencyGroup:'weekly', description:'스타트업·AI·투자 이슈를 깊이 있게 풀어주는 지식 콘텐츠 플랫폼.', url:'https://folin.co', daysSince:1, typical:'주 2회', status:'alive', interests:['AI','스타트업','재테크'], trust:['공식 구독 링크 확인','유료 포함'], origin:'한국', language:'한국어', country:'대한민국', type:'magazine' },
  { id:'yozm-it', name:'요즘IT', category:'테크', frequency:'매일', frequencyGroup:'daily', description:'개발·디자인·기획 실무자가 쓰는 글을 모은 IT 매거진.', url:'https://yozm.wishket.com/magazine/', daysSince:0, typical:'매일', status:'alive', interests:['개발','디자인','커리어'], trust:['공식 구독 링크 확인','무료'], origin:'한국', language:'한국어', country:'대한민국', type:'site' },
  { id:'disquiet', name:'디스콰이엇', category:'스타트업', frequency:'수시', frequencyGroup:'occasional', description:'메이커와 스타트업 팀이 만드는 것을 공유하는 커뮤니티 겸 매거진.', url:'https://disquiet.io/', daysSince:0, typical:'수시 업데이트', status:'alive', interests:['스타트업','디자인','개발'], trust:['공식 구독 링크 확인','무료'], origin:'한국', language:'한국어', country:'대한민국', type:'site' },
  { id:'eoplanet', name:'EO플래닛', category:'스타트업', frequency:'주 2회', frequencyGroup:'weekly', description:'스타트업·벤처투자 인터뷰와 트렌드를 전하는 뉴미디어.', url:'https://eopla.net/', daysSince:1, typical:'주 2회', status:'alive', interests:['스타트업','재테크','커리어'], trust:['공식 구독 링크 확인','무료'], origin:'한국', language:'한국어', country:'대한민국', type:'site' }
);

newsletters.push(
  { id:'wired', name:'Wired', category:'테크', frequency:'매일', frequencyGroup:'daily', description:'기술이 문화·사회를 바꾸는 방식을 깊이 있게 다루는 대표 테크 매거진.', url:'https://www.wired.com/', daysSince:0, typical:'매일', status:'alive', interests:['AI','디자인','문화'], trust:['공식 구독 링크 확인','유료 포함','글로벌 인기'], origin:'글로벌', language:'영어 · 소개 한국어', type:'magazine' },
  { id:'the-atlantic', name:'The Atlantic', category:'문화', frequency:'매일', frequencyGroup:'daily', description:'시사·문화·정치를 깊이 있는 에세이로 풀어내는 미국 대표 매거진.', url:'https://www.theatlantic.com/', daysSince:0, typical:'매일', status:'alive', interests:['시사','문화'], trust:['공식 구독 링크 확인','유료 포함','글로벌 인기'], origin:'글로벌', language:'영어 · 소개 한국어', type:'magazine' },
  { id:'mit-tech-review', name:'MIT Technology Review', category:'테크', frequency:'주 2회', frequencyGroup:'weekly', description:'AI·과학기술의 임팩트를 검증된 저널리즘으로 전하는 매거진.', url:'https://www.technologyreview.com/', daysSince:1, typical:'주 2회', status:'alive', interests:['AI','테크'], trust:['공식 구독 링크 확인','유료 포함','글로벌 인기'], origin:'글로벌', language:'영어 · 소개 한국어', type:'magazine' },
  { id:'karpathy', name:'Andrej Karpathy', category:'AI', frequency:'수시', frequencyGroup:'occasional', description:'전 OpenAI·Tesla AI 리더가 AI 연구·학습법에 대해 남기는 글.', url:'https://x.com/karpathy', daysSince:0, typical:'수시 게시', status:'alive', interests:['AI','개발'], trust:['개인 계정','글로벌 인기'], origin:'글로벌', language:'영어', type:'x' },
  { id:'sama', name:'Sam Altman', category:'AI', frequency:'수시', frequencyGroup:'occasional', description:'OpenAI CEO가 전하는 AI 업계 전략과 방향.', url:'https://x.com/sama', daysSince:0, typical:'수시 게시', status:'alive', interests:['AI','스타트업'], trust:['개인 계정','글로벌 인기'], origin:'글로벌', language:'영어', type:'x' },
  { id:'anthropic-x', name:'Anthropic', category:'AI', frequency:'수시', frequencyGroup:'occasional', description:'Anthropic의 공식 제품·연구 발표 계정.', url:'https://x.com/AnthropicAI', daysSince:0, typical:'수시 게시', status:'alive', interests:['AI'], trust:['공식 계정'], origin:'글로벌', language:'영어', type:'x' },
  { id:'openai-x', name:'OpenAI', category:'AI', frequency:'수시', frequencyGroup:'occasional', description:'OpenAI의 공식 제품·연구 발표 계정.', url:'https://x.com/OpenAI', daysSince:0, typical:'수시 게시', status:'alive', interests:['AI'], trust:['공식 계정'], origin:'글로벌', language:'영어', type:'x' },
  { id:'simonw', name:'Simon Willison', category:'AI', frequency:'수시', frequencyGroup:'occasional', description:'AI 도구·LLM을 실제로 써보고 정리하는 개발자 계정.', url:'https://x.com/simonw', daysSince:0, typical:'수시 게시', status:'alive', interests:['AI','개발'], trust:['개인 계정'], origin:'글로벌', language:'영어', type:'x' },
  { id:'charliebilello', name:'Charlie Bilello', category:'재테크', frequency:'수시', frequencyGroup:'occasional', description:'주식·금리·거시경제 통계를 차트로 정리해 전하는 계정.', url:'https://x.com/charliebilello', daysSince:0, typical:'수시 게시', status:'alive', interests:['재테크','시사'], trust:['개인 계정','글로벌 인기'], origin:'글로벌', language:'영어', type:'x' },
  { id:'zerohedge', name:'ZeroHedge', category:'재테크', frequency:'수시', frequencyGroup:'occasional', description:'속보 위주 금융·경제 뉴스 계정. 관점이 강하니 교차 확인 권장.', url:'https://x.com/zerohedge', daysSince:0, typical:'수시 게시', status:'alive', interests:['재테크','시사'], trust:['개인 계정','관점 강함 · 교차 확인 권장'], origin:'글로벌', language:'영어', type:'x' },
  { id:'naval', name:'Naval Ravikant', category:'자기계발', frequency:'수시', frequencyGroup:'occasional', description:'부·행복에 관한 짧고 철학적인 글로 널리 인용되는 계정.', url:'https://x.com/naval', daysSince:0, typical:'수시 게시', status:'alive', interests:['커리어','자기계발','재테크'], trust:['개인 계정','글로벌 인기'], origin:'글로벌', language:'영어', type:'x' },
  { id:'paulg', name:'Paul Graham', category:'스타트업', frequency:'수시', frequencyGroup:'occasional', description:'Y Combinator 창업자가 남기는 스타트업·창업 에세이와 단상.', url:'https://x.com/paulg', daysSince:0, typical:'수시 게시', status:'alive', interests:['스타트업','커리어'], trust:['개인 계정','글로벌 인기'], origin:'글로벌', language:'영어', type:'x' }
);

newsletters.push(
  { id:'booding', name:'부딩', category:'부동산', frequency:'주 2회', frequencyGroup:'weekly', description:'밀레니얼 실수요자를 위한 부동산 정보를 쉬운 말로 정리하는 뉴스레터.', url:'https://www.booding.co/', daysSince:1, typical:'화·금요일', status:'alive', interests:['부동산','재테크'], trust:['공식 구독 링크 확인','무료'], origin:'한국', language:'한국어', country:'대한민국', type:'newsletter' },
  { id:'maeburi', name:'매부리레터', category:'부동산', frequency:'주 2회', frequencyGroup:'weekly', description:'청약·시황·재건축까지 부동산 재테크 이슈를 상세히 정리하는 뉴스레터.', url:'https://page.stibee.com/subscriptions/110950', daysSince:1, typical:'월·목요일', status:'alive', interests:['부동산','재테크'], trust:['공식 구독 링크 확인','무료'], origin:'한국', language:'한국어', country:'대한민국', type:'newsletter' },
  { id:'surfit', name:'서핏', category:'커리어', frequency:'매일', frequencyGroup:'daily', description:'기획·개발·디자인·마케팅 실무 아티클을 매일 모아 보여주는 커리어 플랫폼.', url:'https://www.surfit.io/', daysSince:0, typical:'매일', status:'alive', interests:['커리어','개발','디자인'], trust:['공식 구독 링크 확인','무료'], origin:'한국', language:'한국어', country:'대한민국', type:'site' },
  { id:'careet', name:'캐릿', category:'마케팅', frequency:'주 2회', frequencyGroup:'weekly', description:'대학내일이 운영하는 Z세대 트렌드·마케팅 인사이트 미디어.', url:'https://www.careet.net/', daysSince:1, typical:'주 2회', status:'alive', interests:['마케팅','문화'], trust:['공식 구독 링크 확인','무료'], origin:'한국', language:'한국어', country:'대한민국', type:'site' },
  { id:'goguma-farm', name:'고구마팜', category:'마케팅', frequency:'주 1회', frequencyGroup:'weekly', description:'밈과 커뮤니티 반응으로 브랜드 트렌드를 읽는 마케팅 뉴스레터.', url:'https://gogumafarm.kr/', daysSince:1, typical:'매주', status:'alive', interests:['마케팅','문화'], trust:['공식 구독 링크 확인','무료'], origin:'한국', language:'한국어', country:'대한민국', type:'site' },
  { id:'designdb', name:'디자인DB', category:'디자인', frequency:'매일', frequencyGroup:'daily', description:'국내 최대 규모의 디자인 트렌드·산업 정보 포털.', url:'https://www.designdb.com/', daysSince:0, typical:'매일', status:'alive', interests:['디자인','문화'], trust:['공식 구독 링크 확인','무료'], origin:'한국', language:'한국어', country:'대한민국', type:'site' },
  { id:'sciencetimes', name:'사이언스타임즈', category:'과학', frequency:'주 1회', frequencyGroup:'weekly', description:'한국과학창의재단이 만드는 과학기술·정책·문화 전문 인터넷 신문.', url:'https://www.sciencetimes.co.kr/main', daysSince:1, typical:'주 1회', status:'alive', interests:['과학','교육'], trust:['공식 구독 링크 확인','무료'], origin:'한국', language:'한국어', country:'대한민국', type:'site' },
  { id:'gmlawcat', name:'굿모닝로캣', category:'법률', frequency:'평일', frequencyGroup:'daily', description:'법률신문이 보내는 아침 법률·판례 뉴스 뉴스레터.', url:'https://gmlawcat.stibee.com/', daysSince:0, typical:'평일 아침', status:'alive', interests:['법률','시사'], trust:['공식 구독 링크 확인','무료'], origin:'한국', language:'한국어', country:'대한민국', type:'newsletter' },
  { id:'gamemeca', name:'게임메카', category:'게임', frequency:'매일', frequencyGroup:'daily', description:'국내 게임 뉴스·순위·공략을 매일 갱신하는 게임 전문 매체.', url:'https://www.gamemeca.com/', daysSince:0, typical:'매일', status:'alive', interests:['게임','문화'], trust:['공식 구독 링크 확인','무료'], origin:'한국', language:'한국어', country:'대한민국', type:'site' },
  { id:'newstravel', name:'뉴스트래블', category:'여행', frequency:'매일', frequencyGroup:'daily', description:'항공·호텔·축제 등 국내외 여행 소식을 매일 전하는 여행 전문 매체.', url:'https://www.newstravel.co.kr/', daysSince:0, typical:'매일', status:'alive', interests:['여행','라이프'], trust:['공식 구독 링크 확인','무료'], origin:'한국', language:'한국어', country:'대한민국', type:'site' },
  { id:'kinolights', name:'키노라이츠', category:'문화', frequency:'매일', frequencyGroup:'daily', description:'OTT·영화·드라마 랭킹과 추천을 통합 제공하는 콘텐츠 플랫폼.', url:'https://www.kinolights.com/', daysSince:0, typical:'매일', status:'alive', interests:['영화','문화'], trust:['공식 구독 링크 확인','무료'], origin:'한국', language:'한국어', country:'대한민국', type:'site' },
  { id:'esg-economy', name:'ESG경제', category:'환경', frequency:'매일', frequencyGroup:'daily', description:'탄소중립·기후기술·ESG 정책을 다루는 전문 매체.', url:'https://www.esgeconomy.com/', daysSince:0, typical:'매일', status:'alive', interests:['환경','재테크'], trust:['공식 구독 링크 확인','무료'], origin:'한국', language:'한국어', country:'대한민국', type:'site' },
  { id:'dallem', name:'달램 웰니스 뉴스레터', category:'건강', frequency:'주 1회', frequencyGroup:'weekly', description:'국내외 웰니스 트렌드와 기업 웰니스 사례를 큐레이션하는 뉴스레터.', url:'https://dallem.stibee.com/', daysSince:1, typical:'수요일 오전 8시', status:'alive', interests:['건강','라이프'], trust:['공식 구독 링크 확인','무료'], origin:'한국', language:'한국어', country:'대한민국', type:'newsletter' },
  { id:'munhak-newsletter', name:'문학동네 책첵레터', category:'문화', frequency:'주 1회', frequencyGroup:'weekly', description:'신간 소식과 책 만드는 사람들의 이야기를 전하는 출판사 뉴스레터.', url:'https://munhak.com/newsletter', daysSince:1, typical:'주 1회', status:'alive', interests:['도서','문화'], trust:['공식 구독 링크 확인','무료'], origin:'한국', language:'한국어', country:'대한민국', type:'newsletter' }
);

newsletters.push(
  { id:'nature', name:'Nature', category:'과학', frequency:'매일', frequencyGroup:'daily', description:'세계에서 가장 권위 있는 과학 학술 매거진으로 최신 연구와 과학 뉴스를 함께 전한다.', url:'https://www.nature.com/', daysSince:0, typical:'매일', status:'alive', interests:['과학','AI'], trust:['공식 구독 링크 확인','유료 포함','글로벌 인기'], origin:'글로벌', language:'영어 · 소개 한국어', type:'magazine' },
  { id:'hubermanlab', name:'Huberman Lab', category:'건강', frequency:'수시', frequencyGroup:'occasional', description:'스탠퍼드 신경과학자가 근거 기반 건강·수면·운동 정보를 전하는 계정.', url:'https://x.com/hubermanlab', daysSince:0, typical:'수시 게시', status:'alive', interests:['건강','과학'], trust:['개인 계정','글로벌 인기'], origin:'글로벌', language:'영어', type:'x' },
  { id:'nomadicmatt', name:'Nomadic Matt', category:'여행', frequency:'주 1회', frequencyGroup:'weekly', description:'예산 여행 팁과 실전 노하우를 오래 쌓아온 여행 블로그.', url:'https://www.nomadicmatt.com/', daysSince:1, typical:'주 1회', status:'alive', interests:['여행','라이프'], trust:['공식 구독 링크 확인','무료','글로벌 인기'], origin:'글로벌', language:'영어 · 소개 한국어', type:'site' },
  { id:'ign', name:'IGN', category:'게임', frequency:'매일', frequencyGroup:'daily', description:'게임·영화·테크 리뷰와 뉴스를 전하는 글로벌 대표 게임 매거진.', url:'https://www.ign.com/', daysSince:0, typical:'매일', status:'alive', interests:['게임','문화'], trust:['공식 구독 링크 확인','무료','글로벌 인기'], origin:'글로벌', language:'영어 · 소개 한국어', type:'magazine' },
  { id:'rogerebert', name:'RogerEbert.com', category:'문화', frequency:'매일', frequencyGroup:'daily', description:'로저 이버트의 정신을 잇는 영화 비평 사이트.', url:'https://www.rogerebert.com/', daysSince:0, typical:'매일', status:'alive', interests:['영화','문화'], trust:['공식 구독 링크 확인','무료','글로벌 인기'], origin:'글로벌', language:'영어 · 소개 한국어', type:'site' },
  { id:'yaleclimate', name:'Yale Climate Connections', category:'환경', frequency:'평일', frequencyGroup:'daily', description:'예일대가 운영하는 기후 과학·정책 저널리즘 사이트.', url:'https://yaleclimateconnections.org/', daysSince:0, typical:'평일', status:'alive', interests:['환경','과학'], trust:['공식 구독 링크 확인','무료','글로벌 인기'], origin:'글로벌', language:'영어 · 소개 한국어', type:'site' }
);

const globalCountries = { 'morning-brew':'미국', 'tldr':'미국', 'rundown-ai':'미국', 'the-hustle':'미국', 'stratechery':'미국', 'the-browser':'영국', 'dense-discovery':'호주', 'three-two-one':'미국', 'hbr-tip':'미국', 'wired':'미국', 'the-atlantic':'미국', 'mit-tech-review':'미국', 'karpathy':'미국', 'sama':'미국', 'anthropic-x':'미국', 'openai-x':'미국', 'simonw':'미국', 'charliebilello':'미국', 'zerohedge':'미국', 'naval':'미국', 'paulg':'미국', 'nature':'영국', 'hubermanlab':'미국', 'nomadicmatt':'미국', 'ign':'미국', 'rogerebert':'미국', 'yaleclimate':'미국' };
newsletters.forEach(item => { if (item.origin === '글로벌') item.country = globalCountries[item.id] || '미국'; });
newsletters.forEach(item => { item.type = item.type || 'newsletter'; });

const $ = (selector) => document.querySelector(selector);
const stored = (key, fallback) => JSON.parse(localStorage.getItem(key) || JSON.stringify(fallback));
const state = { category:'전체', topic:'전체', origin:'전체', country:'전체', frequency:'전체', type:'전체', query:'', sort:'recommended', saved:new Set(stored('letter-shelf', [])), personal:stored('letter-status', {}), interests:stored('letter-interests', []), preferences:stored('letter-preferences', { frequency:'all', paused:false }) };
const readingTimes = { '시사':'3분 읽기', '비즈니스':'4분 읽기', '마케팅':'3분 읽기', '테크':'5분 읽기', '라이프':'3분 읽기', '커리어':'4분 읽기', '재테크':'3분 읽기', '스타트업':'4분 읽기', 'AI':'2분 읽기', '부동산':'4분 읽기', '과학':'4분 읽기', '법률':'3분 읽기', '게임':'3분 읽기', '여행':'3분 읽기', '환경':'4분 읽기', '건강':'3분 읽기' };
const valuePromises = { '시사':'한 줄 요약 뒤에, 왜 중요한지까지 알려줘요.', '비즈니스':'일하는 사람에게 필요한 맥락을 먼저 짚어줘요.', '마케팅':'바로 써먹을 수 있는 브랜드 사례를 골라줘요.', '테크':'링크보다 맥락을 먼저 확인할 수 있어요.', '라이프':'짧게 읽어도 오래 생각할 이야기를 전해요.', '커리어':'내 일과 성장에 연결되는 포인트를 보여줘요.', '재테크':'시장을 보는 관점을 짧게 정리해줘요.', '스타트업':'만드는 사람의 관점에서 흐름을 짚어줘요.', 'AI':'AI 현장의 변화를 가장 빠르게 알려줘요.', '부동산':'실수요자에게 필요한 정보만 골라줘요.', '과학':'검증된 연구를 쉬운 말로 풀어줘요.', '법률':'판례와 제도 변화를 놓치지 않게 해줘요.', '게임':'신작과 업계 소식을 빠르게 훑어줘요.', '여행':'가기 전 알아야 할 실전 정보를 챙겨줘요.', '환경':'기후·ESG 흐름을 놓치지 않게 해줘요.', '건강':'몸과 마음을 챙기는 근거 있는 정보를 줘요.' };
const categories = ['전체', ...new Set(newsletters.map(({category}) => category))];
const topics = ['전체', ...new Set(newsletters.flatMap(({interests}) => interests))];
const origins = [['전체','전체'], ['한국어 뉴스레터','한국'], ['글로벌 원문 · 한국어 소개','글로벌']];
const countries = ['전체', ...new Set(newsletters.map(({country}) => country || '미국'))];
const frequencyFilters = [['전체','전체'], ['매일','daily'], ['주 1회','weekly'], ['가끔만','occasional']];
const interests = ['AI','재테크','커리어','디자인','시사'];
const typeLabels = { newsletter:'뉴스레터', magazine:'매거진', site:'사이트', x:'X 계정' };
const types = ['전체', ...new Set(newsletters.map(({type}) => type))];
const unsubscribeText = { newsletter:'해지 · 원문 메일 하단 수신거부 링크 또는 계정 설정', magazine:'해지 · 구독 관리 페이지 또는 메일 하단 링크', site:'그만 보기 · 즐겨찾기 삭제 또는 방문 중단', x:'그만 보기 · 프로필에서 팔로우 취소' };

function freshness(item) { const verb = (item.type === 'x' || item.type === 'site') ? '확인' : '발행'; if (item.daysSince === 0) return `오늘 ${verb}`; if (item.daysSince === 1) return `어제 ${verb}`; return `${item.daysSince}일째 새 글 없음`; }
function matches(item) { const words = `${item.name} ${item.category} ${item.description} ${item.interests.join(' ')}`.toLowerCase(); return (state.category === '전체' || item.category === state.category) && (state.topic === '전체' || item.interests.includes(state.topic)) && (state.origin === '전체' || item.origin === state.origin) && (state.country === '전체' || item.country === state.country) && (state.frequency === '전체' || item.frequencyGroup === state.frequency) && (state.type === '전체' || item.type === state.type) && words.includes(state.query); }
function issueLink(item) { return `${ISSUE_URL}?title=${encodeURIComponent(`[정보 수정] ${item.name}`)}&body=${encodeURIComponent(`뉴스레터: ${item.name}\n\n수정할 내용:\n\n확인한 링크:`)}`; }

function card(item) {
  const node = $('#newsletter-template').content.firstElementChild.cloneNode(true);
  node.querySelector('.category').textContent = item.category;
  node.querySelector('.type-badge').textContent = typeLabels[item.type] || '뉴스레터';
  node.querySelector('.origin-badge').textContent = item.origin === '글로벌' ? `GLOBAL · ${item.country} · 한국어 소개` : '대한민국 · 한국어 원문';
  node.querySelector('.tag-list').textContent = item.interests.slice(0, 3).map(tag => `#${tag}`).join(' ');
  const status = node.querySelector('.status'); status.textContent = item.status === 'alive' ? (item.type === 'x' ? '활동 중' : '발행 중') : '확인 필요'; if (item.status !== 'alive') status.classList.add('paused');
  node.querySelector('h3').textContent = item.name; node.querySelector('.description').textContent = item.description;
  node.querySelector('.value-promise').textContent = valuePromises[item.category] || '내게 필요한 내용인지 빠르게 확인할 수 있어요.';
  node.querySelector('.frequency').textContent = item.frequency; node.querySelector('.last-issue').textContent = freshness(item);
  node.querySelector('.reading-time').textContent = readingTimes[item.category] || '3분 읽기';
  node.querySelector('.delivery').textContent = `${item.type === 'newsletter' || item.type === 'magazine' ? '평균 발행' : '평소 활동'} · ${item.typical}`;
  node.querySelector('.unsubscribe-help').textContent = unsubscribeText[item.type] || unsubscribeText.newsletter;
  node.querySelector('.trust-badges').replaceChildren(...item.trust.map(label => { const badge = document.createElement('span'); badge.textContent = label; return badge; }));
  const visit = node.querySelector('.visit'); visit.href = item.url;
  node.querySelector('.visit-label').textContent = item.type === 'x' ? '팔로우 · 프로필' : item.type === 'newsletter' ? '구독 · 원문' : '방문하기 · 원문';
  const translate = node.querySelector('.translate'); if (item.origin === '글로벌') { translate.hidden = false; translate.href = `https://translate.google.com/translate?sl=auto&tl=ko&u=${encodeURIComponent(item.url)}`; }
  const save = node.querySelector('.save'); const isSaved = state.saved.has(item.id); save.textContent = isSaved ? '저장됨 ✓' : '+ 내 목록'; save.classList.toggle('saved', isSaved);
  save.addEventListener('click', () => { state.saved.has(item.id) ? state.saved.delete(item.id) : state.saved.add(item.id); localStorage.setItem('letter-shelf', JSON.stringify([...state.saved])); render(); });
  const personal = node.querySelector('.personal-state'); personal.value = state.personal[item.id] || '관심 있음';
  personal.addEventListener('change', () => { state.personal[item.id] = personal.value; localStorage.setItem('letter-status', JSON.stringify(state.personal)); });
  node.querySelector('.report').addEventListener('click', () => window.open(issueLink(item), '_blank', 'noopener'));
  return node;
}

function renderFilters() {
  const render = (target, values, active, set) => { const box = $(target); box.replaceChildren(...values.map(([label, value]) => { const button = document.createElement('button'); button.type = 'button'; button.className = `filter ${value === active ? 'active' : ''}`; button.textContent = label; button.addEventListener('click', () => { set(value); renderFilters(); render(); }); return button; })); };
  render('#filters', categories.map(value => [value, value]), state.category, value => state.category = value);
  render('#topic-filters', topics.map(value => [value === '전체' ? '세부 주제 전체' : `# ${value}`, value]), state.topic, value => state.topic = value);
  render('#frequency-filters', frequencyFilters, state.frequency, value => state.frequency = value);
  render('#origin-filters', origins, state.origin, value => state.origin = value);
  render('#country-filters', countries.map(value => [value === '전체' ? '국가 전체' : value, value]), state.country, value => state.country = value);
  render('#type-filters', types.map(value => [value === '전체' ? '형식 전체' : typeLabels[value], value]), state.type, value => state.type = value);
}
function sortItems(items) { return [...items].sort((a,b) => { if (state.sort === 'recent') return a.daysSince - b.daysSince; if (state.sort === 'light') return (readingTimes[a.category] || '').localeCompare(readingTimes[b.category] || ''); const aMatch = a.interests.filter(interest => state.interests.includes(interest)).length; const bMatch = b.interests.filter(interest => state.interests.includes(interest)).length; return bMatch - aMatch || a.daysSince - b.daysSince; }); }
function renderToday() { const picks = newsletters.filter(item => item.status === 'alive' && item.daysSince <= 1 && (state.preferences.frequency === 'all' || item.frequencyGroup === state.preferences.frequency)).slice(0, 3); $('#today-grid').replaceChildren(...(state.preferences.paused ? [] : picks.map(card))); }
function renderRecommendations() { const section = $('#recommendations'); if (!state.interests.length || state.preferences.paused) { section.hidden = true; return; } const source = newsletters.filter(item => state.preferences.frequency === 'all' || item.frequencyGroup === state.preferences.frequency); const matching = source.filter(item => item.interests.some(interest => state.interests.includes(interest))).sort((a,b) => a.daysSince - b.daysSince); const fallback = source.filter(item => !matching.includes(item)).sort((a,b) => a.daysSince - b.daysSince); const picked = [...matching, ...fallback].slice(0,5); section.hidden = false; $('#interest-name').textContent = state.interests.join(' · '); $('#recommendation-grid').replaceChildren(...picked.map(card)); }
function render() { const items = sortItems(newsletters.filter(matches)); $('#newsletter-grid').replaceChildren(...items.map(card)); $('#result-count').textContent = items.length; const saved = newsletters.filter(item => state.saved.has(item.id)); $('#saved-grid').replaceChildren(...saved.map(card)); $('#empty-state').hidden = saved.length > 0; $('#saved-count').textContent = saved.length; renderRecommendations(); renderToday(); }
function updateSummary() { const alive = newsletters.filter(({status}) => status === 'alive').length; $('#active-total').textContent = newsletters.length; $('#alive-total').textContent = alive; $('#today-count').textContent = newsletters.filter(({daysSince}) => daysSince === 0).length + '개'; $('#paused-count').textContent = newsletters.length - alive + '개'; $('#checked-date').textContent = new Intl.DateTimeFormat('ko-KR', { year:'numeric', month:'2-digit', day:'2-digit' }).format(new Date()); }
function openOnboarding() { const dialog = $('#onboarding'); const options = $('#interest-options'); options.replaceChildren(...interests.map(interest => { const label = document.createElement('label'); const input = document.createElement('input'); input.type = 'checkbox'; input.value = interest; input.checked = state.interests.includes(interest); input.addEventListener('change', () => { if ([...options.querySelectorAll('input:checked')].length > 3) input.checked = false; }); label.append(input, document.createTextNode(interest)); return label; })); dialog.showModal(); }

function openPreferences() { const dialog = $('#preferences'); const box = $('#preference-interests'); box.replaceChildren(...interests.map(interest => { const label = document.createElement('label'); const input = document.createElement('input'); input.type = 'checkbox'; input.value = interest; input.checked = state.interests.includes(interest); label.append(input, document.createTextNode(interest)); return label; })); const frequency = dialog.querySelector(`[name="preference-frequency"][value="${state.preferences.frequency}"]`); if (frequency) frequency.checked = true; $('#pause-recommendations').checked = state.preferences.paused; dialog.showModal(); }
function applyTheme(theme) { document.body.classList.toggle('dark', theme === 'dark'); const toggle = $('#toggle-theme'); toggle.setAttribute('aria-pressed', String(theme === 'dark')); toggle.textContent = theme === 'dark' ? '라이트 모드' : '다크 모드'; }
function applyTextSize(size) { document.body.classList.toggle('large-text', size === 'large'); const toggle = $('#toggle-text-size'); toggle.setAttribute('aria-pressed', String(size === 'large')); toggle.textContent = size === 'large' ? '글자 기본' : '글자 크게'; }
async function applyLinkStatus() { try { const response = await fetch('data/link-status.json', { cache: 'no-store' }); if (!response.ok) return; const { results } = await response.json(); results.filter(item => item.status === 'needs-review').forEach(({ id }) => { const newsletter = newsletters.find(item => item.id === id); if (newsletter) newsletter.status = 'needs-review'; }); updateSummary(); render(); } catch { /* file:// 미리보기에서는 상태 파일을 읽지 못할 수 있음 */ } }

$('#search').addEventListener('input', event => { state.query = event.target.value.trim().toLowerCase(); render(); });
$('#sort').addEventListener('change', event => { state.sort = event.target.value; render(); });
$('#edit-interests').addEventListener('click', openOnboarding);
$('#open-preferences').addEventListener('click', openPreferences);
$('#preferences-form').addEventListener('submit', () => { state.interests = [...$('#preference-interests').querySelectorAll('input:checked')].slice(0,3).map(input => input.value); state.preferences = { frequency: document.querySelector('[name="preference-frequency"]:checked').value, paused: $('#pause-recommendations').checked }; localStorage.setItem('letter-interests', JSON.stringify(state.interests)); localStorage.setItem('letter-preferences', JSON.stringify(state.preferences)); render(); });
$('#toggle-theme').addEventListener('click', () => { const theme = document.body.classList.contains('dark') ? 'light' : 'dark'; localStorage.setItem('letter-theme', theme); applyTheme(theme); });
$('#toggle-text-size').addEventListener('click', () => { const size = document.body.classList.contains('large-text') ? 'normal' : 'large'; localStorage.setItem('letter-text-size', size); applyTextSize(size); });
$('#onboarding-form').addEventListener('submit', () => { state.interests = [...$('#interest-options').querySelectorAll('input:checked')].map(input => input.value); localStorage.setItem('letter-interests', JSON.stringify(state.interests)); render(); });
document.querySelector('.footer-report').addEventListener('click', () => window.open(ISSUE_URL, '_blank', 'noopener'));
applyTheme(localStorage.getItem('letter-theme') || 'light'); applyTextSize(localStorage.getItem('letter-text-size') || 'normal'); updateSummary(); renderFilters(); renderToday(); render(); applyLinkStatus();
if (!localStorage.getItem('letter-onboarding-seen')) { $('#onboarding').addEventListener('close', () => localStorage.setItem('letter-onboarding-seen', 'true'), { once:true }); openOnboarding(); }
