import { Newsletter } from './types';

/**
 * 전 카테고리 무료·정식·합법·비자극 출처 확장.
 * - deskRole info: 뉴스·공공·기관 정보 → 대시보드/리더
 * - deskRole browse: 레퍼런스·커뮤니티 탐색 → 디렉터리「전부」
 * 원문 복제 없음. 공식 링크 + 한국어 소개만.
 */
type Seed = Partial<Newsletter> & {
  id: string;
  name: string;
  category: string;
  siteUrl: string;
  country: string;
};

const I = 'info' as const;
const B = 'browse' as const;

const seed: Seed[] = [
  // —— 시사·국제 (공영·공공) ——
  { id: 'cat-news-kr-yonhap', name: '연합뉴스', category: '시사', siteUrl: 'https://www.yna.co.kr/', country: '대한민국', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '상시', frequencyGroup: 'occasional', description: '국내 대표 통신사. 정치·경제·사회 속보.', interests: ['시사', '국제'], trust: ['통신사', '공식', '무료 열람'] },
  { id: 'cat-news-kr-kbs', name: 'KBS 뉴스', category: '시사', siteUrl: 'https://news.kbs.co.kr/', country: '대한민국', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '상시', frequencyGroup: 'occasional', description: '한국 공영방송 뉴스. 시사·재난 정보.', interests: ['시사'], trust: ['공영', '무료'] },
  { id: 'cat-news-kr-mbc', name: 'MBC 뉴스', category: '시사', siteUrl: 'https://imnews.imbc.com/', country: '대한민국', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '상시', frequencyGroup: 'occasional', description: '지상파 뉴스·시사 콘텐츠 공식.', interests: ['시사'], trust: ['방송사', '공식'] },
  { id: 'cat-news-kr-sbs', name: 'SBS 뉴스', category: '시사', siteUrl: 'https://news.sbs.co.kr/', country: '대한민국', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '상시', frequencyGroup: 'occasional', description: 'SBS 뉴스 공식. 국내외 시사.', interests: ['시사'], trust: ['방송사', '공식'] },
  { id: 'cat-news-us-ap', name: 'AP News', category: '국제', siteUrl: 'https://apnews.com/', country: '미국', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '상시', frequencyGroup: 'occasional', description: 'Associated Press. 팩트 중심 국제 통신.', interests: ['국제', '시사'], trust: ['통신사', '무료 열람'] },
  { id: 'cat-news-us-reuters', name: 'Reuters', category: '국제', siteUrl: 'https://www.reuters.com/', country: '미국', industry: '미디어', type: 'site', deskRole: I, stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '상시', frequencyGroup: 'occasional', description: '로이터 국제 뉴스·비즈니스. 무료 기사 다수.', interests: ['국제', '재테크'], trust: ['통신사', '공식'] },
  { id: 'cat-news-jp-nhk', name: 'NHK ニュース', category: '시사', siteUrl: 'https://www3.nhk.or.jp/news/', country: '일본', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '일본어 · 소개 한국어', frequency: '상시', frequencyGroup: 'occasional', description: '일본 공영 NHK 국내 뉴스.', interests: ['시사', '국제'], trust: ['공영', '무료'] },
  { id: 'cat-news-cn-xinhua', name: '新华网 Xinhua', category: '국제', siteUrl: 'https://www.news.cn/', country: '중국', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '중국어·영어 · 소개 한국어', frequency: '상시', frequencyGroup: 'occasional', description: '신화통신 공식 사이트. 중국·국제 뉴스.', interests: ['국제', '시사'], trust: ['통신사', '공식'] },
  { id: 'cat-news-eu-europarl', name: 'European Parliament News', category: '국제', siteUrl: 'https://www.europarl.europa.eu/news/en', country: '벨기에', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '영어 외 · 소개 한국어', frequency: '수시', frequencyGroup: 'occasional', description: '유럽의회 공식 뉴스·의정 정보.', interests: ['국제', '정책'], trust: ['EU 공식', '무료'] },
  { id: 'cat-news-un', name: 'UN News', category: '국제', siteUrl: 'https://news.un.org/', country: '미국', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '다국어 · 소개 한국어', frequency: '상시', frequencyGroup: 'occasional', description: '유엔 공식 뉴스. 인도·기후·평화 이슈.', interests: ['국제', '환경', '정책'], trust: ['UN 공식', '무료'] },

  // —— 과학·테크·AI 정보 ——
  { id: 'cat-sci-kr-kisti', name: '과학기술정보 KISTI', category: '과학', siteUrl: 'https://www.kisti.re.kr/', country: '대한민국', industry: '과학', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '수시', frequencyGroup: 'occasional', description: '과학기술 정보·데이터 공공 기관.', interests: ['과학', '테크'], trust: ['공공', '공식'] },
  { id: 'cat-sci-kr-nst', name: '국가과학기술연구회', category: '과학', siteUrl: 'https://www.nst.re.kr/', country: '대한민국', industry: '과학', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '수시', frequencyGroup: 'occasional', description: '출연연 연구 성과·과학 정책 정보.', interests: ['과학'], trust: ['공공', '공식'] },
  { id: 'cat-sci-us-nasa-science', name: 'NASA Science', category: '과학', siteUrl: 'https://science.nasa.gov/', country: '미국', industry: '항공우주', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '상시', frequencyGroup: 'occasional', description: 'NASA 과학 미션·우주·지구 관측 정보.', interests: ['과학', '우주'], trust: ['공공', '무료'] },
  { id: 'cat-sci-us-nist', name: 'NIST News', category: '과학', siteUrl: 'https://www.nist.gov/news-events/news', country: '미국', industry: '과학', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '수시', frequencyGroup: 'occasional', description: '미국 표준기술연구소. 계측·사이버·과학 뉴스.', interests: ['과학', '테크'], trust: ['공공', '공식'] },
  { id: 'cat-sci-us-sciencedaily', name: 'ScienceDaily', category: '과학', siteUrl: 'https://www.sciencedaily.com/', country: '미국', industry: '과학', type: 'site', deskRole: I, stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '매일', frequencyGroup: 'daily', description: '대학·연구소 보도자료 기반 과학 뉴스 요약.', interests: ['과학'], trust: ['과학 뉴스', '무료 열람'] },
  { id: 'cat-sci-eu-cern', name: 'CERN News', category: '과학', siteUrl: 'https://home.cern/news', country: '스위스', industry: '과학', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '수시', frequencyGroup: 'occasional', description: '유럽입자물리연구소 공식 뉴스.', interests: ['과학'], trust: ['연구기관', '공식'] },
  { id: 'cat-tech-us-ars', name: 'Ars Technica', category: '테크', siteUrl: 'https://arstechnica.com/', country: '미국', industry: 'AI', type: 'magazine', deskRole: I, stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '매일', frequencyGroup: 'daily', description: '기술·정책·과학을 심층으로 다루는 테크 매체 (무료 기사 다수).', interests: ['테크', 'AI', '시사'], trust: ['테크 저널리즘', '공식'] },
  { id: 'cat-tech-us-theverge', name: 'The Verge', category: '테크', siteUrl: 'https://www.theverge.com/', country: '미국', industry: 'AI', type: 'magazine', deskRole: I, stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '매일', frequencyGroup: 'daily', description: '가젯·인터넷·문화 테크 뉴스.', interests: ['테크', '문화'], trust: ['테크 매체', '공식'] },
  { id: 'cat-tech-kr-bloter', name: '블로터', category: '테크', siteUrl: 'https://www.bloter.net/', country: '대한민국', industry: 'AI', type: 'site', deskRole: I, stability: 'high', origin: '한국', language: '한국어', frequency: '매일', frequencyGroup: 'daily', description: '한국 IT·미디어 산업 전문 매체.', interests: ['테크', '미디어'], trust: ['전문 매체', '공식'] },
  { id: 'cat-tech-kr-zdnet', name: 'ZDNet Korea', category: '테크', siteUrl: 'https://zdnet.co.kr/', country: '대한민국', industry: 'AI', type: 'site', deskRole: I, stability: 'high', origin: '한국', language: '한국어', frequency: '매일', frequencyGroup: 'daily', description: 'IT·엔터프라이즈·보안 뉴스.', interests: ['테크', '보안'], trust: ['IT 매체', '공식'] },

  // —— 건강·의료 (공공) ——
  { id: 'cat-health-kr-kdca', name: '질병관리청', category: '건강', siteUrl: 'https://www.kdca.go.kr/', country: '대한민국', industry: '바이오', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '수시', frequencyGroup: 'occasional', description: '감염병·예방접종·건강 통계 공공 정보.', interests: ['건강', '의료'], trust: ['공공', '공식'] },
  { id: 'cat-health-kr-mohw', name: '보건복지부', category: '의료', siteUrl: 'https://www.mohw.go.kr/', country: '대한민국', industry: '바이오', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '수시', frequencyGroup: 'occasional', description: '보건·복지 정책·보도자료 공식.', interests: ['의료', '정책'], trust: ['정부', '공식'] },
  { id: 'cat-health-who', name: 'WHO', category: '건강', siteUrl: 'https://www.who.int/', country: '스위스', industry: '바이오', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '영어 외 · 소개 한국어', frequency: '수시', frequencyGroup: 'occasional', description: '세계보건기구. 글로벌 보건 가이드·뉴스.', interests: ['건강', '국제'], trust: ['UN 산하', '공식', '무료'] },
  { id: 'cat-health-us-cdc', name: 'U.S. CDC', category: '건강', siteUrl: 'https://www.cdc.gov/', country: '미국', industry: '바이오', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '수시', frequencyGroup: 'occasional', description: '미국 질병통제예방센터. 역학·예방 정보.', interests: ['건강', '의료'], trust: ['공공', '공식'] },
  { id: 'cat-health-us-nih', name: 'NIH', category: '의료', siteUrl: 'https://www.nih.gov/', country: '미국', industry: '바이오', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '수시', frequencyGroup: 'occasional', description: '미국 국립보건원. 연구·건강 정보.', interests: ['의료', '과학'], trust: ['공공', '공식'] },
  { id: 'cat-health-us-medline', name: 'MedlinePlus', category: '건강', siteUrl: 'https://medlineplus.gov/', country: '미국', industry: '바이오', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '영어·스페인어 · 소개 한국어', frequency: '상시', frequencyGroup: 'occasional', description: '일반인용 신뢰 건강 정보 (NLM).', interests: ['건강', '교육'], trust: ['공공', '무료', '비자극 안내'] },

  // —— 환경·에너지·기후 ——
  { id: 'cat-env-kr-me', name: '환경부', category: '환경', siteUrl: 'https://www.me.go.kr/', country: '대한민국', industry: '에너지', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '수시', frequencyGroup: 'occasional', description: '환경 정책·대기·폐기물 공공 정보.', interests: ['환경', '정책'], trust: ['정부', '공식'] },
  { id: 'cat-env-kr-airkorea', name: '에어코리아', category: '환경', siteUrl: 'https://www.airkorea.or.kr/', country: '대한민국', industry: '에너지', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '상시', frequencyGroup: 'occasional', description: '대기질 실시간 공공 측정 정보.', interests: ['환경', '건강'], trust: ['공공', '실시간'] },
  { id: 'cat-env-unep', name: 'UNEP', category: '환경', siteUrl: 'https://www.unep.org/', country: '케냐', industry: '에너지', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '수시', frequencyGroup: 'occasional', description: '유엔환경계획. 기후·생물다양성 정보.', interests: ['환경', '국제'], trust: ['UN', '공식'] },
  { id: 'cat-env-ipcc', name: 'IPCC', category: '환경', siteUrl: 'https://www.ipcc.ch/', country: '스위스', industry: '에너지', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '수시', frequencyGroup: 'occasional', description: '기후변화에 관한 정부간 협의체 보고서·뉴스.', interests: ['환경', '과학'], trust: ['과학 합의', '공식'] },
  { id: 'cat-env-us-noaa', name: 'NOAA', category: '환경', siteUrl: 'https://www.noaa.gov/', country: '미국', industry: '에너지', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '상시', frequencyGroup: 'occasional', description: '미국 해양대기청. 기상·해양·기후 데이터.', interests: ['환경', '과학'], trust: ['공공', '무료'] },
  { id: 'cat-env-eu-eea', name: 'European Environment Agency', category: '환경', siteUrl: 'https://www.eea.europa.eu/', country: '덴마크', industry: '에너지', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '수시', frequencyGroup: 'occasional', description: '유럽환경청. EU 환경 지표·보고서.', interests: ['환경', '정책'], trust: ['EU', '공식'] },

  // —— 법률·정책·공공 데이터 ——
  { id: 'cat-law-kr-law', name: '국가법령정보센터', category: '법률', siteUrl: 'https://www.law.go.kr/', country: '대한민국', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '상시', frequencyGroup: 'occasional', description: '대한민국 법령·판례·행정규칙 공식 검색.', interests: ['법률', '정책'], trust: ['정부', '공식', '무료'] },
  { id: 'cat-law-kr-assembly', name: '국회 의안정보시스템', category: '정책', siteUrl: 'https://likms.assembly.go.kr/', country: '대한민국', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '수시', frequencyGroup: 'occasional', description: '국회의안·입법 진행 공공 정보.', interests: ['정책', '시사'], trust: ['국회', '공식'] },
  { id: 'cat-law-eu-eurlex', name: 'EUR-Lex', category: '법률', siteUrl: 'https://eur-lex.europa.eu/', country: '룩셈부르크', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '다국어 · 소개 한국어', frequency: '상시', frequencyGroup: 'occasional', description: 'EU 법률·관보 공식 데이터베이스.', interests: ['법률', '국제'], trust: ['EU', '무료'] },
  { id: 'cat-law-us-congress', name: 'Congress.gov', category: '정책', siteUrl: 'https://www.congress.gov/', country: '미국', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '상시', frequencyGroup: 'occasional', description: '미국 의회 법안·의사록 공식.', interests: ['정책', '국제'], trust: ['정부', '무료'] },
  { id: 'cat-data-kr-data', name: '공공데이터포털', category: '시사', siteUrl: 'https://www.data.go.kr/', country: '대한민국', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '상시', frequencyGroup: 'occasional', description: '한국 공공데이터 개방·API 포털.', interests: ['시사', '테크', '정책'], trust: ['공공', '무료'] },
  { id: 'cat-data-us-data', name: 'Data.gov', category: '시사', siteUrl: 'https://data.gov/', country: '미국', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '상시', frequencyGroup: 'occasional', description: '미국 연방 공공데이터 포털.', interests: ['시사', '테크'], trust: ['공공', '무료'] },

  // —— 재테크·경제 공공 ——
  { id: 'cat-fin-kr-bok', name: '한국은행', category: '재테크', siteUrl: 'https://www.bok.or.kr/', country: '대한민국', industry: '금융', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '수시', frequencyGroup: 'occasional', description: '통화정책·경제통계 공식 발표.', interests: ['재테크', '시사'], trust: ['중앙은행', '공식'] },
  { id: 'cat-fin-kr-fss', name: '금융감독원', category: '재테크', siteUrl: 'https://www.fss.or.kr/', country: '대한민국', industry: '금융', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '수시', frequencyGroup: 'occasional', description: '금융소비자 보호·감독 공시 정보.', interests: ['재테크'], trust: ['공공', '공식'] },
  { id: 'cat-fin-kr-mosf', name: '기획재정부', category: '재테크', siteUrl: 'https://www.moef.go.kr/', country: '대한민국', industry: '금융', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '수시', frequencyGroup: 'occasional', description: '재정·세제·거시경제 정책 보도.', interests: ['재테크', '정책'], trust: ['정부', '공식'] },
  { id: 'cat-fin-us-fed', name: 'Federal Reserve', category: '재테크', siteUrl: 'https://www.federalreserve.gov/', country: '미국', industry: '금융', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '수시', frequencyGroup: 'occasional', description: '연준 공식. 금리·경제 전망 자료.', interests: ['재테크', '국제'], trust: ['중앙은행', '공식'] },
  { id: 'cat-fin-eu-ecb', name: 'European Central Bank', category: '재테크', siteUrl: 'https://www.ecb.europa.eu/', country: '독일', industry: '금융', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '수시', frequencyGroup: 'occasional', description: '유럽중앙은행. 통화·금융안정 정보.', interests: ['재테크', '국제'], trust: ['중앙은행', '공식'] },
  { id: 'cat-fin-imf', name: 'IMF', category: '재테크', siteUrl: 'https://www.imf.org/', country: '미국', industry: '금융', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '수시', frequencyGroup: 'occasional', description: '국제통화기금. 세계 경제 전망·보고서.', interests: ['재테크', '국제'], trust: ['국제기구', '무료 보고서'] },
  { id: 'cat-fin-worldbank', name: 'World Bank', category: '재테크', siteUrl: 'https://www.worldbank.org/', country: '미국', industry: '금융', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '수시', frequencyGroup: 'occasional', description: '세계은행. 개발·빈곤·데이터 공개.', interests: ['재테크', '국제', '교육'], trust: ['국제기구', '무료'] },

  // —— 커리어·노동·통계 ——
  { id: 'cat-job-kr-moel', name: '고용노동부', category: '커리어', siteUrl: 'https://www.moel.go.kr/', country: '대한민국', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '수시', frequencyGroup: 'occasional', description: '고용·노동 정책·최저임금 등 공공 정보.', interests: ['커리어', '정책'], trust: ['정부', '공식'] },
  { id: 'cat-job-kr-work24', name: '고용24 (Work24)', category: '커리어', siteUrl: 'https://www.work24.go.kr/', country: '대한민국', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '상시', frequencyGroup: 'occasional', description: '공공 취업·직업훈련 통합 포털.', interests: ['커리어', '교육'], trust: ['공공', '무료'] },
  { id: 'cat-job-kr-kostat', name: '통계청', category: '시사', siteUrl: 'https://kostat.go.kr/', country: '대한민국', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '수시', frequencyGroup: 'occasional', description: '국가 통계·인구·물가 공식 발표.', interests: ['시사', '재테크'], trust: ['공공', '공식'] },
  { id: 'cat-job-us-bls', name: 'U.S. BLS', category: '커리어', siteUrl: 'https://www.bls.gov/', country: '미국', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '수시', frequencyGroup: 'occasional', description: '미국 노동통계국. 고용·임금 데이터.', interests: ['커리어', '재테크'], trust: ['공공', '무료'] },

  // —— 문화·도서·음악 (합법 공개) ——
  { id: 'cat-cul-kr-nl', name: '국립중앙도서관', category: '문화', siteUrl: 'https://www.nl.go.kr/', country: '대한민국', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '상시', frequencyGroup: 'occasional', description: '국가 문헌·디지털 도서관 공공 서비스.', interests: ['문화', '교육', '도서'], trust: ['공공', '공식'] },
  { id: 'cat-cul-kr-kcisa', name: '문화포털', category: '문화', siteUrl: 'https://www.culture.go.kr/', country: '대한민국', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '상시', frequencyGroup: 'occasional', description: '공연·전시·축제 공공 문화 정보.', interests: ['문화', '미술'], trust: ['공공', '무료 정보'] },
  { id: 'cat-cul-gutenberg', name: 'Project Gutenberg', category: '문화', siteUrl: 'https://www.gutenberg.org/', country: '미국', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '영어 외 · 소개 한국어', frequency: '상시', frequencyGroup: 'occasional', description: '퍼블릭 도메인 전자책 무료 도서관.', interests: ['문화', '교육', '도서'], trust: ['비영리', '합법 공개', '무료'] },
  { id: 'cat-cul-archive-texts', name: 'Internet Archive · Texts', category: '문화', siteUrl: 'https://archive.org/details/texts', country: '미국', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '상시', frequencyGroup: 'occasional', description: '디지털 도서·사료 아카이브 (합법 공개 범위).', interests: ['문화', '교육'], trust: ['비영리', '무료'] },
  { id: 'cat-music-imslp', name: 'IMSLP / Petrucci Music', category: '음악', siteUrl: 'https://imslp.org/', country: '캐나다', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '상시', frequencyGroup: 'occasional', description: '퍼블릭 도메인 악보 라이브러리. 합법 무료.', interests: ['음악', '문화', '교육'], trust: ['PD 악보', '합법', '무료'] },
  { id: 'cat-music-fma', name: 'Free Music Archive', category: '음악', siteUrl: 'https://freemusicarchive.org/', country: '미국', industry: '미디어', type: 'site', deskRole: I, stability: 'medium', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '상시', frequencyGroup: 'occasional', description: '크리에이티브 커먼즈 음악 아카이브. 라이선스 확인 후 사용.', interests: ['음악', '문화'], trust: ['CC 라이선스', '합법'] },
  { id: 'cat-music-musopen', name: 'Musopen', category: '음악', siteUrl: 'https://musopen.org/', country: '미국', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '상시', frequencyGroup: 'occasional', description: '퍼블릭 도메인 클래식 음원·악보.', interests: ['음악', '교육'], trust: ['PD', '무료'] },
  { id: 'cat-music-kr-kocaca', name: '예술경영지원센터', category: '문화', siteUrl: 'https://www.gokams.or.kr/', country: '대한민국', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '수시', frequencyGroup: 'occasional', description: '공연·예술 산업 공공 지원·통계 정보.', interests: ['문화', '음악'], trust: ['공공', '공식'] },

  // —— 스포츠 (공식·공영) ——
  { id: 'cat-spo-olympics', name: 'Olympics.com', category: '스포츠', siteUrl: 'https://olympics.com/', country: '스위스', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '영어 외 · 소개 한국어', frequency: '상시', frequencyGroup: 'occasional', description: '국제올림픽위원회 공식. 경기·선수 정보.', interests: ['스포츠'], trust: ['공식', '합법'] },
  { id: 'cat-spo-fifa', name: 'FIFA', category: '스포츠', siteUrl: 'https://www.fifa.com/', country: '스위스', industry: '미디어', type: 'site', deskRole: I, stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '상시', frequencyGroup: 'occasional', description: '국제축구연맹 공식 뉴스·대회 정보.', interests: ['스포츠'], trust: ['공식'] },
  { id: 'cat-spo-kr-koc', name: '대한체육회', category: '스포츠', siteUrl: 'https://www.sports.or.kr/', country: '대한민국', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '수시', frequencyGroup: 'occasional', description: '한국 체육 정책·종목 정보 공식.', interests: ['스포츠'], trust: ['공공·협회', '공식'] },
  { id: 'cat-spo-bbc-sport', name: 'BBC Sport', category: '스포츠', siteUrl: 'https://www.bbc.com/sport', country: '영국', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '상시', frequencyGroup: 'occasional', description: 'BBC 공영 스포츠 뉴스 (자극적 가십 최소화).', interests: ['스포츠', '시사'], trust: ['공영', '무료'] },

  // —— 여행 (공식 관광청) ——
  { id: 'cat-travel-kr-visitkorea', name: 'VisitKorea', category: '여행', siteUrl: 'https://korean.visitkorea.or.kr/', country: '대한민국', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '상시', frequencyGroup: 'occasional', description: '한국관광공사 공식 여행 정보.', interests: ['여행', '문화'], trust: ['공공', '공식', '무료'] },
  { id: 'cat-travel-jp-jnto', name: 'Japan National Tourism', category: '여행', siteUrl: 'https://www.japan.travel/', country: '일본', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '다국어 · 소개 한국어', frequency: '상시', frequencyGroup: 'occasional', description: '일본정부관광국 공식 여행 안내.', interests: ['여행'], trust: ['공공', '공식'] },
  { id: 'cat-travel-us-nps', name: 'U.S. National Park Service', category: '여행', siteUrl: 'https://www.nps.gov/', country: '미국', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '상시', frequencyGroup: 'occasional', description: '미국 국립공원 공식. 안전·탐방 정보.', interests: ['여행', '환경'], trust: ['공공', '무료 정보'] },
  { id: 'cat-travel-eu-visit', name: 'VisitEurope (ETC)', category: '여행', siteUrl: 'https://visiteurope.com/', country: '벨기에', industry: '미디어', type: 'site', deskRole: I, stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '상시', frequencyGroup: 'occasional', description: '유럽 관광 공식 연합 안내.', interests: ['여행', '문화'], trust: ['공식 관광'] },
  { id: 'cat-travel-cn-cta', name: 'China Tourism (공식 영문 안내)', category: '여행', siteUrl: 'https://www.travelchina.gov.cn/', country: '중국', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'medium', origin: '글로벌', language: '영어·중국어 · 소개 한국어', frequency: '상시', frequencyGroup: 'occasional', description: '중국 공식 관광 정보 창구 (접속 환경에 따라 다를 수 있음).', interests: ['여행'], trust: ['공공·공식'] },

  // —— 음식·농업 (공공) ——
  { id: 'cat-food-fao', name: 'FAO', category: '음식', siteUrl: 'https://www.fao.org/', country: '이탈리아', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '영어 외 · 소개 한국어', frequency: '수시', frequencyGroup: 'occasional', description: '유엔식량농업기구. 식량·농업 데이터.', interests: ['음식', '환경', '국제'], trust: ['UN', '공식'] },
  { id: 'cat-food-kr-mfds', name: '식품의약품안전처', category: '음식', siteUrl: 'https://www.mfds.go.kr/', country: '대한민국', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '수시', frequencyGroup: 'occasional', description: '식품·의약품 안전 공지·회수 정보.', interests: ['음식', '건강'], trust: ['정부', '공식'] },
  { id: 'cat-food-kr-atis', name: '농사로·농업기술', category: '농업', siteUrl: 'https://www.nongsaro.go.kr/', country: '대한민국', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '상시', frequencyGroup: 'occasional', description: '농촌진흥청 농업 기술·정보 포털.', interests: ['농업', '음식'], trust: ['공공', '무료'] },
  { id: 'cat-food-us-usda', name: 'USDA', category: '음식', siteUrl: 'https://www.usda.gov/', country: '미국', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '수시', frequencyGroup: 'occasional', description: '미국 농무부. 식품·농업 공공 정보.', interests: ['음식', '농업'], trust: ['공공', '공식'] },

  // —— 육아·교육 보조 공공 ——
  { id: 'cat-parent-kr-mogef', name: '여성가족부', category: '육아', siteUrl: 'https://www.mogef.go.kr/', country: '대한민국', industry: '교육', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '수시', frequencyGroup: 'occasional', description: '가족·아동 정책·지원 공공 정보.', interests: ['육아', '정책'], trust: ['정부', '공식'] },
  { id: 'cat-parent-kr-childcare', name: '아이사랑 보육포털', category: '육아', siteUrl: 'https://www.childcare.go.kr/', country: '대한민국', industry: '교육', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '상시', frequencyGroup: 'occasional', description: '어린이집·보육 공공 정보 서비스.', interests: ['육아'], trust: ['공공', '공식'] },
  { id: 'cat-edu-kr-moe', name: '교육부', category: '교육', siteUrl: 'https://www.moe.go.kr/', country: '대한민국', industry: '교육', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '수시', frequencyGroup: 'occasional', description: '교육 정책·입시·학교 관련 공식 발표.', interests: ['교육', '정책'], trust: ['정부', '공식'] },

  // —— 자동차·교통 공공 ——
  { id: 'cat-auto-kr-molit', name: '국토교통부', category: '자동차', siteUrl: 'https://www.molit.go.kr/', country: '대한민국', industry: '자동차', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '수시', frequencyGroup: 'occasional', description: '교통·주택·항공 정책 공공 정보.', interests: ['자동차', '정책', '부동산'], trust: ['정부', '공식'] },
  { id: 'cat-auto-kr-ts', name: '교통안전공단 / 자동차 리콜', category: '자동차', siteUrl: 'https://www.car.go.kr/', country: '대한민국', industry: '자동차', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '수시', frequencyGroup: 'occasional', description: '자동차 리콜·안전 검사 공공 정보.', interests: ['자동차', '안전'], trust: ['공공', '공식'] },
  { id: 'cat-auto-us-nhtsa', name: 'NHTSA', category: '자동차', siteUrl: 'https://www.nhtsa.gov/', country: '미국', industry: '자동차', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '수시', frequencyGroup: 'occasional', description: '미국 도로교통안전국. 리콜·안전 등급.', interests: ['자동차', '안전'], trust: ['공공', '공식'] },

  // —— 부동산·주거 공공 ——
  { id: 'cat-home-kr-reb', name: '한국부동산원', category: '부동산', siteUrl: 'https://www.reb.or.kr/', country: '대한민국', industry: '금융', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '수시', frequencyGroup: 'occasional', description: '부동산 통계·시세·정책 관련 공공 정보.', interests: ['부동산', '재테크'], trust: ['공공', '공식'] },
  { id: 'cat-home-kr-seoul', name: '서울 부동산 정보광장', category: '부동산', siteUrl: 'https://land.seoul.go.kr/', country: '대한민국', industry: '금융', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '상시', frequencyGroup: 'occasional', description: '서울시 부동산 실거래·정보 공개.', interests: ['부동산'], trust: ['지자체', '공식'] },

  // —— 사진·디자인 정보 (합법·비자극, 탐색은 browse 일부) ——
  { id: 'cat-photo-kr-photodot', name: '포토닷 / 한국사진기자협회 뉴스', category: '사진', siteUrl: 'https://www.photonews.kr/', country: '대한민국', industry: '미디어', type: 'site', deskRole: I, stability: 'medium', origin: '한국', language: '한국어', frequency: '매일', frequencyGroup: 'daily', description: '보도사진·사진 업계 뉴스 (일반 뉴스 톤).', interests: ['사진', '시사'], trust: ['업계 매체'] },
  { id: 'cat-design-us-aiga', name: 'AIGA Eye on Design', category: '디자인', siteUrl: 'https://eyeondesign.aiga.org/', country: '미국', industry: '패션', type: 'site', deskRole: I, stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '주 수회', frequencyGroup: 'weekly', description: '미국 디자인 협회 미디어. 디자인 문화·산업 기사.', interests: ['디자인', '문화'], trust: ['협회', '공식'] },

  // —— 게임: 공식·건전 정보만 (불법 롬/치트 사이트 제외) ——
  { id: 'cat-game-kr-grac', name: '게임물관리위원회', category: '게임', siteUrl: 'https://www.grac.or.kr/', country: '대한민국', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '수시', frequencyGroup: 'occasional', description: '게임 등급·정책 공공 정보. 불법 유통 안내와 무관한 공식 창구.', interests: ['게임', '정책'], trust: ['공공', '공식'] },
  { id: 'cat-game-us-esa', name: 'ESA (Entertainment Software Assoc.)', category: '게임', siteUrl: 'https://www.theesa.com/', country: '미국', industry: '미디어', type: 'site', deskRole: I, stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '수시', frequencyGroup: 'occasional', description: '미국 게임 산업 협회. 산업 통계·정책 (콘텐츠 자체 아님).', interests: ['게임', '정책'], trust: ['협회', '공식'] },

  // —— 패션: 박물관·공공 아카이브 위주 (자극 광고 최소화) ——
  { id: 'cat-fash-met-costume', name: 'The Met · Costume Institute', category: '패션', siteUrl: 'https://www.metmuseum.org/about-the-met/collection-areas/the-costume-institute', country: '미국', industry: '패션', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '상시', frequencyGroup: 'occasional', description: '메트 의상 연구소. 패션사·전시 정보.', interests: ['패션', '미술', '문화'], trust: ['미술관', '공식'] },
  { id: 'cat-fash-vam', name: 'V&A Museum', category: '패션', siteUrl: 'https://www.vam.ac.uk/', country: '영국', industry: '패션', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '상시', frequencyGroup: 'occasional', description: '빅토리아 앨버트 박물관. 디자인·패션 컬렉션 정보.', interests: ['패션', '디자인', '문화'], trust: ['박물관', '공식'] },

  // —— 반도체·산업 추가 정보 ——
  { id: 'cat-semi-us-semi', name: 'SEMI', category: '반도체', siteUrl: 'https://www.semi.org/', country: '미국', industry: '반도체', type: 'site', deskRole: I, stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '수시', frequencyGroup: 'occasional', description: '글로벌 반도체 산업 협회. 뉴스·표준 정보.', interests: ['반도체', '테크'], trust: ['협회', '공식'] },
  { id: 'cat-semi-kr-kisi', name: '한국반도체산업협회', category: '반도체', siteUrl: 'https://www.ksia.or.kr/', country: '대한민국', industry: '반도체', type: 'site', deskRole: I, stability: 'high', origin: '한국', language: '한국어', frequency: '수시', frequencyGroup: 'occasional', description: '국내 반도체 산업 동향·협회 공지.', interests: ['반도체'], trust: ['협회', '공식'] },

  // —— 로봇·우주 정보 ——
  { id: 'cat-robot-ieee', name: 'IEEE Spectrum', category: '로봇공학', siteUrl: 'https://spectrum.ieee.org/', country: '미국', industry: 'AI', type: 'magazine', deskRole: I, stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '매일', frequencyGroup: 'daily', description: 'IEEE 테크 매거진. 로봇·AI·에너지 심층 (무료 기사 다수).', interests: ['로봇공학', 'AI', '테크'], trust: ['학회', '공식'] },
  { id: 'cat-space-esa-edu', name: 'ESA Kids / Education', category: '과학', siteUrl: 'https://www.esa.int/Education', country: '프랑스', industry: '항공우주', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '수시', frequencyGroup: 'occasional', description: '유럽우주국 교육·대중 과학 자료.', interests: ['과학', '교육', '우주'], trust: ['공공', '교육'] },

  // —— 마케팅·비즈 정보 (합법 교육 톤) ——
  { id: 'cat-biz-kr-kita', name: '한국무역협회', category: '비즈니스', siteUrl: 'https://www.kita.net/', country: '대한민국', industry: '금융', type: 'site', deskRole: I, stability: 'high', origin: '한국', language: '한국어', frequency: '수시', frequencyGroup: 'occasional', description: '무역·수출 통계·시장 정보.', interests: ['비즈니스', '재테크'], trust: ['협회', '공식'] },
  { id: 'cat-biz-kr-mss', name: '중소벤처기업부', category: '스타트업', siteUrl: 'https://www.mss.go.kr/', country: '대한민국', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '수시', frequencyGroup: 'occasional', description: '중소·벤처 정책·지원 사업 공고.', interests: ['스타트업', '정책'], trust: ['정부', '공식'] },
  { id: 'cat-biz-us-sba', name: 'U.S. SBA', category: '비즈니스', siteUrl: 'https://www.sba.gov/', country: '미국', industry: '금융', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '수시', frequencyGroup: 'occasional', description: '미국 중소기업청. 창업·지원 공공 가이드.', interests: ['비즈니스', '커리어'], trust: ['공공', '공식'] },

  // —— HR ——
  { id: 'cat-hr-kr-hrdkorea', name: '한국산업인력공단', category: 'HR', siteUrl: 'https://www.hrdkorea.or.kr/', country: '대한민국', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '수시', frequencyGroup: 'occasional', description: '국가기술자격·직업훈련 공공 정보.', interests: ['HR', '커리어', '교육'], trust: ['공공', '공식'] },

  // —— 세무 공공 ——
  { id: 'cat-tax-kr-nts', name: '국세청', category: '세무', siteUrl: 'https://www.nts.go.kr/', country: '대한민국', industry: '금융', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '수시', frequencyGroup: 'occasional', description: '세금 신고·세법 안내 공식.', interests: ['세무', '재테크'], trust: ['정부', '공식'] },
  { id: 'cat-tax-us-irs', name: 'IRS', category: '세무', siteUrl: 'https://www.irs.gov/', country: '미국', industry: '금융', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '수시', frequencyGroup: 'occasional', description: '미국 국세청. 세무 안내 (영문).', interests: ['세무'], trust: ['정부', '공식'] },

  // —— 크립토: 규제·교육 공식만 (투기 커뮤니티·불법 거래소 제외) ——
  { id: 'cat-crypto-kr-fsc', name: '금융위원회 (디지털자산 공지)', category: '크립토', siteUrl: 'https://www.fsc.go.kr/', country: '대한민국', industry: '금융', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '수시', frequencyGroup: 'occasional', description: '디지털자산·금융 정책 공식 보도. 투자 권유 아님.', interests: ['크립토', '정책', '재테크'], trust: ['정부', '공식'] },
  { id: 'cat-crypto-us-sec', name: 'U.S. SEC', category: '크립토', siteUrl: 'https://www.sec.gov/', country: '미국', industry: '금융', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '수시', frequencyGroup: 'occasional', description: '미국 증권거래위원회. 투자자 보호·공시.', interests: ['크립토', '재테크', '정책'], trust: ['규제 기관', '공식'] },

  // —— 반려동물 공공 ——
  { id: 'cat-pet-kr-animal', name: '동물보호관리시스템', category: '반려동물', siteUrl: 'https://www.animal.go.kr/', country: '대한민국', industry: '미디어', type: 'site', deskRole: I, sourceScope: 'public', stability: 'high', origin: '한국', language: '한국어', frequency: '상시', frequencyGroup: 'occasional', description: '유기동물·등록 등 공공 동물보호 정보.', interests: ['반려동물', '정책'], trust: ['공공', '공식'] },

  // —— 리더십·자기계발: 공공·대학 공개 자료 ——
  { id: 'cat-lead-hbr-free', name: 'HBR Ascend / free articles', category: '리더십', siteUrl: 'https://hbr.org/topic/subject/leadership', country: '미국', industry: '미디어', type: 'magazine', deskRole: I, stability: 'high', origin: '글로벌', language: '영어 · 소개 한국어', frequency: '수시', frequencyGroup: 'occasional', description: '하버드비즈니스리뷰 리더십 토픽 (무료 기사 구간 확인).', interests: ['리더십', '커리어'], trust: ['공식', '일부 무료'] },

  // —— 탐색 전용 browse (디렉터리「전부」·갤러리; 리더 기본 제외) ——
  { id: 'cat-browse-pixiv', name: 'pixiv', category: '미술', siteUrl: 'https://www.pixiv.net/', country: '일본', industry: '미술', type: 'site', deskRole: B, stability: 'high', origin: '글로벌', language: '일본어·영어 · 소개 한국어', frequency: '상시', frequencyGroup: 'occasional', description: '일러스트 커뮤니티 탐색용. 리더 정보 추출보다 사이트 방문 권장.', interests: ['미술', '일러스트'], trust: ['정식 서비스', '연령 설정 확인'] },
  { id: 'cat-browse-pinterest', name: 'Pinterest', category: '미술', siteUrl: 'https://www.pinterest.com/', country: '미국', industry: '미술', type: 'site', deskRole: B, stability: 'high', origin: '글로벌', language: '다국어 · 소개 한국어', frequency: '상시', frequencyGroup: 'occasional', description: '이미지 보드 탐색용. 뉴스 리더 대상 아님.', interests: ['미술', '디자인'], trust: ['정식 서비스'] },
];

export const expandRaw: Partial<Newsletter>[] = seed.map(s => ({
  ...s,
  url: s.siteUrl,
  daysSince: s.daysSince ?? 1,
  typical: s.typical ?? '수시',
  status: s.status ?? 'alive',
  interests: s.interests ?? [s.category],
  trust: s.trust ?? ['정식·합법 출처', '공식 링크'],
  origin: s.origin ?? (s.country === '대한민국' ? '한국' : '글로벌'),
  language: s.language ?? '영어 · 소개 한국어',
  type: s.type ?? 'site',
  reuseLevel: 'A',
  sourceScope: s.sourceScope ?? 'general',
  stability: s.stability ?? 'high',
  frequency: s.frequency ?? '수시',
  frequencyGroup: s.frequencyGroup ?? 'occasional',
  deskRole: s.deskRole ?? 'info',
  industry: s.industry,
}));
